#!/bin/sh
#
# As of 0.13, xmonad --recompile will look for a custom build script.

set -e

stack build :xmonad-exe --verbosity error
stack install :xmonad-exe --local-bin-path bin/ --verbosity error
mv bin/xmonad-exe "$1"
