name:                xmonad-bison
version:             0.1.0.0
github:              "githubuser/xmonad"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/githubuser/xmonad#readme>

dependencies:
- base >= 4.7 && < 5
- xmonad
- xmonad-contrib
- containers
- unix

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  xmonad-exe:
    main:                xmonad.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  xmonad-def:
    main:                Main.hs
    source-dirs:         bare
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

